apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}-secret
  namespace: ${NAME}
data:
  DB2INST1_PASSWORD: ZGIyaW5zdDE=  #db2inst1
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
spec:
  type: ClusterIP
  selector:
    app: ${NAME}
  ports:
    - name: ${NAME}-http
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: ${NAME}-https
      protocol: TCP
      port: 50001
      targetPort: 50001
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-lb
spec:
  selector:
    app: ${NAME}
  type: LoadBalancer
  ports:
    - name: ${NAME}-http
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: ${NAME}-https
      protocol: TCP
      port: 50001
      targetPort: 50001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${NAME}
spec:
  selector:
    matchLabels:
      app: ${NAME}
  serviceName: "${NAME}"
  replicas: 1
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      serviceAccount: ${NAME}
      containers:
      - name: ${NAME}
        securityContext:
          privileged: true
        image: ibmcom/db2
        env:
        - name: DB2INST1_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: ${NAME}-secret
              key: DB2INST1_PASSWORD
        - name: LICENSE 
          value: accept 
        - name: DB2INSTANCE 
          value: db2inst1 
        - name: DBNAME
          value: BLUDB
        ports:
        - containerPort: 50000
          name: ${NAME}-http
        - containerPort: 50001
          name: ${NAME}-https
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /database
          name: db2vol
  volumeClaimTemplates:
  - metadata:
      name: db2vol
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 20Gi
      storageClassName: ibmc-file-gold
